### ISSUE TITLE
Estilização da gitpage usando mkdocs

### ISSUE THREAD

**Issue by devMarcosVM** [unb-mds/2024-1-Squad07#15]
## Descrição
A página do GitHub estava utilizando o tema padrão, sem personalização. Decidimos customizá-la para proporcionar uma experiência visual mais agradável e alinhada com nossa identidade visual

## Tarefas
- [x] Pesquisar temas e filtrar cores requisitadas pelo projeto feito no figma.
- [x] Aprender como funciona o mkdocs e seu material
- [x] Implementar no arquivo principal do projeto

## Validação

- [x] Validar com os integrantes do grupo a primeira versão da git page.

**Comment by devMarcosVM** [comment]
Após uma busca, identifiquei um problema ao tentar personalizar as cores no MkDocs. Parece que tanto a notação hexadecimal quanto a RGB não estão sendo aceitas, mesmo quando uso um arquivo style CSS extra. É um contratempo, mas vou continuar procurando soluções alternativas para contornar essa questão. Talvez experimentar com nomes de cores CSS possa funcionar. Vou também dar uma olhada em fóruns online para ver se outros usuários têm enfrentado o mesmo problema e encontraram alguma solução.

**Comment by rafaelcarvalhoj** [comment]
Boa noite, Marcos!
No seu commit 7a02de9 referente a esta issue você adicionou a pasta **site**, mas não era necessário. O processo de deploy da página no workflow "Deploy Documentation Page" no arquivo *jekyll-gh-pages.yml* já faz o build e o deploy automático da página, então não é necessário enviar a pasta **site** nos commits de atualização da documentação.

**Comment by devMarcosVM** [comment]
Boa noite, Rafael!
Agradeço pela sugestão! Optei por adicionar, já que observei em outro projeto que eles incluíram a pasta **site**. Assim que possível, vou removê-la do projeto.
