### ISSUE TITLE
Selecionar tecnologias 

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-Squad07#4]
## Descrição
[Descrição detalhada do problema ou da tarefa.]}
Forneça informações claras e concisas para que outros membros da equipe possam entender o contexto e a importância do problema.

## Tarefas
Liste as tarefas específicas que precisam ser concluídas para resolver o problema ou concluir a tarefa, dívida tarefas grandes e complexas em tarefas simples.
- [x] Realizar uma análise de requisitos para identificar as necessidades técnicas do projeto.
- [x] Pesquisar e avaliar as tecnologias disponíveis que atendam aos requisitos do projeto.
- [x] Discutir e analisar as vantagens e desvantagens de cada tecnologia em potencial.
- [x] Selecionar as tecnologias mais adequadas com base na análise realizada.
- [x] Documentar as tecnologias selecionadas e os motivos de suas escolhas.

## Testes / Avaliação
- [x] Verificar a compatibilidade das tecnologias selecionadas com os requisitos funcionais e não funcionais do projeto.

**Comment by rafaelcarvalhoj** [comment]
# Análise do Projeto para Levantar Tecnologias Necessárias
Dado o objetivo principal do projeto, criar uma plataforma online de análise e armazenamento de dados de licitações relacionadas aos gastos culturais apoiados pelo Governo Federal no estado de Minas Gerais, é indispensável a seleção apropriada das tecnologias para o projeto. As tecnologias abaixo foram estudas para cada caso de uso, desde uso geral até usos específicos.

# Funcionalidades Previstas
Analisando os requisitos do projeto podemos identificar algumas funcionalidades, e com base nelas buscamos as tecnologias mais apropriada para cada situação.

## Coleta de Dados
A parte da coleta de dados é uma das mais importantes do projeto, e baseado na API do querido diário, encontramos algumas tecnologias que podem nos ajudar durante o processo de desenvolvimento e de produção, sendo elas:
- *[Python](https://www.python.org/)*: Linguagem de programação para fazer os limpadores de dados na Web
- Framework *[Scrapy](https://scrapy.org/)*: Framework Python para trabalhar com spiders(limpadores da Web). Através das spiders podemos fazer raspagem de dados na web
- *[Beautiful Soup](https://beautiful-soup-4.readthedocs.io/en/latest/)*: Biblioteca Python que permite fazer a conversão de elementos HTML em strings. E não apenas isso, mas também nós permite buscar por classes, id's e tipo de dados dentro do documento HTML.
- *[Selenium](https://www.selenium.dev/)*: Biblioteca Python para interagir com o browser. Permite fazer buscas que necessitam de interação com a interface.

## Análise e Armazenamento
A análise dos dados podem ser feitas tanto de forma iterativas, na interface web, quanto do lado do servidor, e para isso temos duas abordagens diferentes:
### Análise
Para a análise do lado do **servidor**, podemos utilizar tanto o a API em *[Python](https://www.python.org/)* quanto uma API em *[Node.js](https://nodejs.org/en)*.

Para análise dos dados do lado do **cliente**, há diversas bibliotecas para o *[React](https://react.dev/)*, que permite o desenvolvimento de gráficos e renderização dos dados de forma dinâmica.
### Armazenamento
No armazenamento temos duas opções muito atrativas, o *[MongoDB](https://www.mongodb.com/pt-br)* e o *[Postgres](https://www.postgresql.org/)*. Ambos são ótimos para armazenar os dados, mas para cada parte da aplicação precisamos decidir se um modelo relacional, otimizado para buscas complexas e inserção é melhor que um modelo não-relacional, com liberdade de estrutura e organização por documentos.

## Visualização de Dados
Quando se trata de visualização, estamos tratando da nossa interface Web, que sem dúvidas um ótimo framework para resolver este problema é o *[Next.js](https://nextjs.org/)*. Ele permite fazer renderização do lado do servidor, trabalhar com rotas de uma forma descomplicada, estrutura de pastas dinâmicas e diversas outras features.
Como o *[Next.js](https://nextjs.org/)* é um framework construído por cima do *[React](https://react.dev/)*, podemos utilizar muitas bibliotecas para plotagem dos dados, dentre elas se destacam: *[React-Charts](https://react-charts.tanstack.com/)* e a *[Apexcharts](https://react-charts.tanstack.com/)*. Fica a critério do time em tempo de desenvolvimento decidir quais são as mais adequadas para cada situação.

## API Intermediária
Uma das idéias é fazer um sistema de notificação para avisar aos inscritos da plataforma sobre novas licitações com gastos culturais do estado de Minas Gerais, também queremos salvas algumas licitações no nosso banco de dados, e para fazer todo esse trabalho uma ótima ferramenta é o *[Node.js](https://nodejs.org/en)*, dado que nós estaremos trabalhando com *[Next.js](https://nextjs.org/)*, trabalhar com a mesma linguagem tanto do lado do servidor quanto do lado do cliente otimiza os estudos e o tempo de desenvolvimento do time. Para fazer essa API, podemos utilizar algumas bibliotecas, sendo elas:

- *[Express](https://expressjs.com/)*: Criação de servidor para receber requisições HTTP e processar os dados.
- *[Nodemailer](https://www.nodemailer.com/)*: Enviar emails de dentro da nossa aplicação para os inscritos da plataforma.
- *[Prisma](https://www.prisma.io/)*: ORM para manipulação dos bancos de dados.

## Infraestrutura
Uma parte importante da nossa aplicação é aonde vamos publicar. Como não temos uma plataforma definitiva, é crucial desenvolver todo o ecossistema em microsserviços. Com o *[Docker](https://www.docker.com/)* podemos desenvolver a aplicação em um ambiente controlado, onde determinamos de ponta a ponta os recursos que vão ser utilizados, bibliotecas que vão ser instaladas e configuração de rede para a comunicação dos microsserviços.
