### ISSUE TITLE
Elicitação de requisitos

### ISSUE THREAD

**Issue by Gxaite** [unb-mds/2024-1-Squad07#5]
## Descrição
O projeto necessita eliciar e documentar os requisitos do sistema para garantir que todas as partes interessadas tenham uma compreensão clara e concisa do que será desenvolvido. Essa etapa é fundamental para orientar o desenvolvimento e garantir que o produto final atenda às expectativas e necessidades dos usuários e do cliente.

## Tarefas
- [x] Realizar workshops de brainstorming com a equipe para coletar e analisar ideias e requisitos.
- [x] Utilizar técnicas como histórias de usuários, casos de uso e diagramas de fluxo para capturar e documentar os requisitos.

## Testes / Avaliação
- [x] Revisar os requisitos documentados para garantir que sejam claros, consistentes, completos e não ambíguos.
- [ ] Verificar se os requisitos capturam todas as funcionalidades e características necessárias para o sistema.
- [ ] Assegurar que os requisitos são mensuráveis e testáveis, permitindo a validação do sistema durante o desenvolvimento e após a implementação.
- [ ] Validar os requisitos

**Comment by devMarcosVM** [comment]
Em reunião pensamos em conjunto e escrevemos ideias para os requisitos: https://docs.google.com/document/d/1ZkIXs7EkNb3z5jdXlI8fsAW0gqsjpof7Oyczeg9RP2U/edit?usp=sharing

**Comment by devMarcosVM** [comment]
Em reunião pensamos em conjunto e escrevemos ideias para os requisitos: https://docs.google.com/document/d/1ZkIXs7EkNb3z5jdXlI8fsAW0gqsjpof7Oyczeg9RP2U/edit?usp=sharing
